### ISSUE TITLE
Failure to install `spacy==2.0.11`

### ISSUE THREAD

**Issue by infojunkie** [Ahmid/TwitterFeedMonitor#2]
Truing to build `docker build -t ner-service:v1 .` locally, getting the following error:
```
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a8z6ujtk/spacy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_1ly2aze/install-record.txt --single-version-externally-managed --compile" failed with error code -9 in /tmp/pip-install-a8z6ujtk/spacy/
```

at the line 
```  
Running setup.py install for spacy: started
    Running setup.py install for spacy: still running...
    Running setup.py install for spacy: still running...
    Running setup.py install for spacy: still running...
    Running setup.py install for spacy: still running...
    Running setup.py install for spacy: finished with status 'error'
```
Complete output attached: [error.txt](https://github.com/Ahmid/TwitterFeedMonitor/files/1945017/error.txt)

**Comment by infojunkie** [comment]
Fyi I updated `requirements.txt` from `spacy==2.0.10` to `spacy==2.0.11` but it made no difference.

**Comment by Ahmid** [comment]
Please try to remove the line `spacy==2.0.10` fom `requirements.txt`, and add the line `pip install -U spacy` in Dockerfile just after the line `RUN pip install --no-cache-dir -r requirements.txt` and before `COPY . .`
